### ISSUE TITLE
how to turn off customMetrics, performanceCounters and metrics

### ISSUE THREAD

**Issue by r-michal-ah** [microsoft/ApplicationInsights-Java#3492]
Hello, 

I still cannot find clear answer to this question: https://github.com/microsoft/ApplicationInsights-Java/issues/1905. I would like to do exactly the same thing, I want to keep **requests**, **exceptions** and **traces** in AI. The rest should be turn off. How to do it? I have spring boot application with kafka and mongo. Will below configuration work? 

```yaml
  "instrumentation": {
    "azureSdk": {
      "enabled": false
    },
    "kafka": {
      "enabled": false
    },
    "micrometer": {
      "enabled": false
    },
    "mongo": {
      "enabled": false
    }
  }
```
And what about default metrics from https://github.com/microsoft/ApplicationInsights-Java/wiki/Default-Metrics-Captured-by-Java-3.0-Agent? Is there any property I could use to turn it off? Or I need to use metric filter (https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-telemetry-processors#metric-filter)
